/*User Defined Types*/
IF NOT EXISTS(SELECT * FROM UserDefinedTypes WHERE Name = N'SRO_PCAR_Risk')
    INSERT INTO UserDefinedTypes (Name, [Description])
    VALUES ('SRO_PCAR_Risk', 'วิเคราะห์ความเสี่ยง')
IF NOT EXISTS(SELECT * FROM UserDefinedTypes WHERE Name = N'SRO_PCAR_Cause_Man')
    INSERT INTO UserDefinedTypes (Name, [Description])
    VALUES ('SRO_PCAR_Cause_Man', 'สรุปปัญหา/สาเหตุเกิดจาก - คน')
IF NOT EXISTS(SELECT * FROM UserDefinedTypes WHERE Name = N'SRO_PCAR_Cause_Machine')
    INSERT INTO UserDefinedTypes (Name, [Description])
    VALUES ('SRO_PCAR_Cause_Machine', 'สรุปปัญหา/สาเหตุเกิดจาก - เครื่องจักร')
IF NOT EXISTS(SELECT * FROM UserDefinedTypes WHERE Name = N'SRO_PCAR_Cause_Material')
    INSERT INTO UserDefinedTypes (Name, [Description])
    VALUES ('SRO_PCAR_Cause_Material', 'สรุปปัญหา/สาเหตุเกิดจาก - วัสดุ')
IF NOT EXISTS(SELECT * FROM UserDefinedTypes WHERE Name = N'SRO_PCAR_Cause_Method')
    INSERT INTO UserDefinedTypes (Name, [Description])
    VALUES ('SRO_PCAR_Cause_Method', 'สรุปปัญหา/สาเหตุเกิดจาก - วิธีการ')
IF NOT EXISTS(SELECT * FROM UserDefinedTypes WHERE Name = N'SRO_PCAR_Cause_Environment')
    INSERT INTO UserDefinedTypes (Name, [Description])
    VALUES ('SRO_PCAR_Cause_Environment', 'สรุปปัญหา/สาเหตุเกิดจาก - สิ่งแวดล้อม')

/*User Defined Type Values*/
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R01')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R01', 'อันตรายต่อผู้ปฏิบัติงาน')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R02')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R02', 'อันตรายเกิดอัคคีภัย')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R03')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R03', 'มีผลต่อสภาพแวดล้อมการทำงาน')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R04')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R04', 'การมองเห็นและการเข้าถึง')    
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R05')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R05', 'Productivity')  
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R06')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R06', 'Defect')      
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R07')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R07', 'Performance')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R08')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R08', 'Cost')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Risk' AND Value = 'R09')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Risk', 'R09', 'Other')

IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Man' AND Value = 'C10')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Man', 'C10', '-')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Man' AND Value = 'C11')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Man', 'C11', 'ไม่รู้มาตรฐาน')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Man' AND Value = 'C12')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Man', 'C12', 'ไม่ทำตามมาตรฐาน')

IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Machine' AND Value = 'C20')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Machine', 'C20', '-')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Machine' AND Value = 'C21')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Machine', 'C21', 'ออกแบบไม่ดี')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Machine' AND Value = 'C22')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Machine', 'C22', 'ไม่ได้กำหนดมาตรฐาน')

IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Material' AND Value = 'C30')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Material', 'C30', '-')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Material' AND Value = 'C31')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Material', 'C31', 'ไม่ได้กำหนดมาตรฐาน')
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Material' AND Value = 'C32')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Material', 'C32', 'กำหนดไม่เหมาะสม')

IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Method' AND Value = 'C40')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Method', 'C40', '-')    
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Method' AND Value = 'C41')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Method', 'C41', 'ไม่มีมาตรฐาน')       
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Method' AND Value = 'C42')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Method', 'C42', 'กำหนดไม่เหมาะสม')     

IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Environment' AND Value = 'C50')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Environment', 'C50', '-')   
IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Environment' AND Value = 'C51')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Environment', 'C51', 'ไม่มีมาตรฐาน')     

IF NOT EXISTS(SELECT * FROM UserDefinedTypeValues WHERE TypeName = N'SRO_PCAR_Cause_Environment' AND Value = 'C52')
    INSERT INTO UserDefinedTypeValues (TypeName, [Value], [Description])
    VALUES ('SRO_PCAR_Cause_Environment', 'C52', 'กำหนดไม่เหมาะสม')      